behaviors:
  Bomberman:
    trainer_type: sac
    hyperparameters:
      batch_size: 256
      buffer_size: 51200
      learning_rate: 3e-4
      init_entcoef: 0.5
      tau: 0.005
      steps_per_update: 1
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: resnet
      memory:
        memory_size: 64
        sequence_length: 32
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 5000000
    time_horizon: 64
    summary_freq: 10000
    threaded: true
    self_play:
      save_steps: 60000
      team_change: 300000
      swap_steps: 60000
      window: 20
      play_against_latest_model_ratio: 0.5