behaviors:
  Bomberman:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 25600
      learning_rate: 3e-4
      epsilon: 0.2
      lambd: 0.92
      num_epoch: 6
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: resnet
      memory:
        memory_size: 128
        sequence_length: 64
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 64
    summary_freq: 2000
    threaded: true
    self_play:
      save_steps: 60000
      team_change: 300000
      swap_steps: 60000
      window: 20
      play_against_latest_model_ratio: 0.5